const surahs = [
    {
      id: 1,
      arabic: 'الفاتحة',
      english: 'Al-Fatiha',
      bangla: 'আল ফাতিহা',
      meaning: 'সূচনা',
      ayah: 7,
      ruku: 1,
      meccan: true,
    },
    {
      id: 2,
      arabic: 'البقرة',
      english: 'Al-Baqara',
      bangla: 'আল বাকারা',
      meaning: 'বকনা-বাছুর-গরু',
      ayah: 286,
      ruku: 40,
      meccan: false,
    },
    {
      id: 3,
      arabic: 'آل عمران',
      english: 'Al Imran',
      bangla: 'আল ইমরান',
      meaning: 'ইমরানের পরিবার',
      ayah: 200,
      ruku: 20,
      meccan: false,
    },
    {
      id: 4,
      arabic: 'النساء',
      english: 'An-Nisa',
      bangla: 'আন নিসা',
      meaning: 'মহিলা',
      ayah: 176,
      ruku: 24,
      meccan: false,
    },
    {
      id: 5,
      arabic: 'المآئدة',
      english: 'Al-Ma idah',
      bangla: 'আল মায়িদাহ',
      meaning: 'খাদ্য পরিবেশিত টেবিল',
      ayah: 120,
      ruku: 16,
      meccan: false,
    },
    {
      id: 6,
      arabic: 'الانعام',
      english: 'Al-An am',
      bangla: 'আল আনআম',
      meaning: 'গৃহপালিত পশু',
      ayah: 165,
      ruku: 20,
      meccan: true,
    },
    {
      id: 7,
      arabic: 'الأعراف',
      english: 'Al-A raf',
      bangla: 'আল আরাফ',
      meaning: 'উচু স্থানসমূহ',
      ayah: 206,
      ruku: 24,
      meccan: true,
    },
    {
      id: 8,
      arabic: 'الأنفال',
      english: 'Al-Anfal',
      bangla: 'আল আনফাল',
      meaning: 'যুদ্ধে-লব্ধ ধনসম্পদ',
      ayah: 75,
      ruku: 10,
      meccan: false,
    },
    {
      id: 9,
      arabic: 'التوبة',
      english: 'At-Tawbah',
      bangla: 'আত-তাওবাহ্‌',
      meaning: 'অনুশোচনা',
      ayah: 129,
      ruku: 16,
      meccan: false,
    },
    {
      id: 10,
      arabic: 'يونس',
      english: 'Yunus',
      bangla: 'ইউনুস',
      meaning: 'নবী ইউনুস',
      ayah: 109,
      ruku: 11,
      meccan: true,
    },
    {
      id: 11,
      arabic: 'هود',
      english: 'Hud',
      bangla: 'হুদ',
      meaning: 'নবী হুদ',
      ayah: 123,
      ruku: 10,
      meccan: true,
    },
    {
      id: 12,
      arabic: 'يوسف',
      english: 'Yusuf',
      bangla: 'ইউসুফ',
      meaning: 'নবী ইউসুফ',
      ayah: 111,
      ruku: 12,
      meccan: true,
    },
    {
      id: 13,
      arabic: 'الرّعد',
      english: 'Ar-Ra d',
      bangla: 'আর-রাদ',
      meaning: 'বজ্রনাদ',
      ayah: 43,
      ruku: 6,
      meccan: false,
    },
    {
      id: 14,
      arabic: 'إبراهيم',
      english: 'Ibrahim',
      bangla: 'ইব্রাহীম',
      meaning: 'নবী ইব্রাহিম',
      ayah: 52,
      ruku: 7,
      meccan: true,
    },
    {
      id: 15,
      arabic: 'الحجر',
      english: 'Al-Hijr',
      bangla: ' আল হিজর',
      meaning: 'পাথুরে পাহাড়',
      ayah: 99,
      ruku: 6,
      meccan: true,
    },
    {
      id: 16,
      arabic: 'النّحل',
      english: 'An-Nahl',
      bangla: 'আন নাহল',
      meaning: 'মৌমাছি',
      ayah: 128,
      ruku: 16,
      meccan: true,
    },
    {
      id: 17,
      arabic: 'الإسرا',
      english: 'Bani Israil',
      bangla: 'বনী-ইসরাঈল',
      meaning: 'ইসরায়েলের সন্তানগণ',
      ayah: 111,
      ruku: 12,
      meccan: true,
    },
    {
      id: 18,
      arabic: 'الكهف',
      english: 'Al-Kahf',
      bangla: 'আল কাহফ',
      meaning: 'গুহা',
      ayah: 110,
      ruku: 12,
      meccan: true,
    },
    {
      id: 19,
      arabic: 'مريم',
      english: 'Maryam',
      bangla: 'মারইয়াম',
      meaning: 'মারিয়াম (নবী ঈসার মা)',
      ayah: 98,
      ruku: 6,
      meccan: true,
    },
    {
      id: 20,
      arabic: 'طه',
      english: 'Twa-ha',
      bangla: 'ত্বোয়া-হা',
      meaning: 'ত্বোয়া-হা',
      ayah: 135,
      ruku: 8,
      meccan: true,
    },
    {
      id: 21,
      arabic: 'الأنبياء',
      english: 'Al-Anbiya',
      bangla: 'আল আম্বিয়া',
      meaning: 'নবীগণ',
      ayah: 112,
      ruku: 7,
      meccan: true,
    },
    {
      id: 22,
      arabic: 'الحجّ',
      english: 'Al-Hajj',
      bangla: 'আল হাজ্জ্ব',
      meaning: 'হাজ্জ',
      ayah: 78,
      ruku: 10,
      meccan: false,
    },
    {
      id: 23,
      arabic: 'المؤمنون',
      english: 'Al-Mu minun',
      bangla: 'আল মুমিনূন',
      meaning: 'বিশ্বাসীগণ',
      ayah: 118,
      ruku: 6,
      meccan: false,
    },
    {
      id: 24,
      arabic: 'النّور',
      english: 'An-Nur',
      bangla: 'আন নূর',
      meaning: 'আলো,জ্যোতি',
      ayah: 64,
      ruku: 9,
      meccan: false,
    },
    {
      id: 25,
      arabic: 'الفرقان',
      english: 'Al-Furqan',
      bangla: 'আল ফুরকান',
      meaning: 'সত্য মিথ্যার পার্থক্য নির্ধারণকারী গ্রন্থ',
      ayah: 77,
      ruku: 6,
      meccan: true,
    },
    {
      id: 26,
      arabic: 'الشّعراء',
      english: 'Ash-Shu ara',
      bangla: 'আশ শুআরা',
      meaning: 'কবিগণ',
      ayah: 227,
      ruku: 11,
      meccan: true,
    },
    {
        id: 27,
        arabic: 'النّمل',
        english: 'An-Naml',
        bangla: 'আন নম্‌ল',
        meaning: 'পিপীলিকা',
        ayah: 93,
        ruku: 7,
        meccan: true,
      },
      {
        id: 28,
        arabic: 'القصص',
        english: 'Al-Qasas',
        bangla: 'আল কাসাস',
        meaning: 'ঘটনা,কাহিনী',
        ayah: 88,
        ruku: 9,
        meccan: true,
      },
      {
        id: 29,
        arabic: 'العنكبوت',
        english: 'Al-Ankabut',
        bangla: 'আল আনকাবূত',
        meaning: 'মাকড়সা',
        ayah: 69,
        ruku: 7,
        meccan: false,
      },
      {
        id: 30,
        arabic: 'الرّوم',
        english: 'Ar-Rum',
        bangla: 'আর রুম',
        meaning: 'রোমান জাতি',
        ayah: 60,
        ruku: 6,
        meccan: false,
      },
      {
        id: 31,
        arabic: 'لقمان',
        english: 'Luqman',
        bangla: 'লোক্‌মান',
        meaning: 'একজন জ্ঞানী ব্যক্তি',
        ayah: 34,
        ruku: 4,
        meccan: true,
      },
      {
        id: 32,
        arabic: 'السّجدة',
        english: 'As-Sajdah',
        bangla: 'আস সেজদাহ্',
        meaning: 'সিজদাহ',
        ayah: 30,
        ruku: 3,
        meccan: false,
      },
      {
        id: 33,
        arabic: 'الْأحزاب',
        english: 'Al-Ahzab',
        bangla: 'আল আহ্‌যাব',
        meaning: 'জোট বা দলসমূহ',
        ayah: 73,
        ruku: 9,
        meccan: false,
      },
      {
        id: 34,
        arabic: 'سبا',
        english: 'Saba',
        bangla: 'সাবা',
        meaning: 'রানী সাবা',
        ayah: 54,
        ruku: 6,
        meccan: true,
      },
      {
        id: 35,
        arabic: 'فاطر',
        english: 'Fatir',
        bangla: 'ফাতির',
        meaning: 'আদি স্রষ্টা',
        ayah: 45,
        ruku: 5,
        meccan: true,
      },
      {
        id: 36,
        arabic: 'يس',
        english: 'Ya-Sin',
        bangla: 'ইয়াসীন',
        meaning: 'ইয়াসীন',
        ayah: 83,
        ruku: 5,
        meccan: true,
      },
      {
        id: 37,
        arabic: 'الصّافات',
        english: 'As-Saffat',
        bangla: 'আস ছাফ্‌ফাত',
        meaning: 'সারিবদ্ধভাবে দাড়ানো',
        ayah: 182,
        ruku: 5,
        meccan: true,
      },
      {
        id: 38,
        arabic: 'ص',
        english: 'Sad',
        bangla: 'ছোয়াদ',
        meaning: 'আরবি বর্ণ',
        ayah: 88,
        ruku: 5,
        meccan: true,
      },
      {
        id: 39,
        arabic: 'الزّمر',
        english: 'Az-Zumar',
        bangla: 'আয্‌-যুমার',
        meaning: 'দল-বদ্ধ জনতা',
        ayah: 75,
        ruku: 8,
        meccan: true,
      },
      {
        id: 40,
        arabic: 'غافر',
        english: 'Ghafir',
        bangla: 'গাফির',
        meaning: 'ক্ষমাশীল',
        ayah: 85,
        ruku: 9,
        meccan: true,
      },
      {
        id: 41,
        arabic: 'فصّلت',
        english: 'Ha-Mim Sajdah',
        bangla: 'হা-মীম সেজদাহ্‌',
        meaning: 'সুস্পষ্ট বিবরণ',
        ayah: 54,
        ruku: 6,
        meccan: true,
      },
      {
        id: 42,
        arabic: 'الشّورى',
        english: 'Ash-Shura',
        bangla: 'আশ্‌-শূরা',
        meaning: 'পরামর্শ',
        ayah: 53,
        ruku: 5,
        meccan: true,
      },
      {
        id: 43,
        arabic: 'الزّخرف',
        english: 'Az-Zukhruf',
        bangla: 'আয্‌-যুখরুফ',
        meaning: 'সোনাদানা',
        ayah: 89,
        ruku: 7,
        meccan: true,
      },
      {
        id: 44,
        arabic: 'الدّخان',
        english: 'Ad-Dukhan',
        bangla: 'আদ-দোখান',
        meaning: 'ধোঁয়া',
        ayah: 59,
        ruku: 3,
        meccan: true,
      },
      {
        id: 45,
        arabic: 'الجاثية',
        english: 'Al-Jathiya',
        bangla: 'আল জাসিয়াহ',
        meaning: 'নতজানু',
        ayah: 37,
        ruku: 4,
        meccan: true,
      },
      {
        id: 46,
        arabic: 'الأحقاف',
        english: 'Al-Ahqaf',
        bangla: 'আল আহ্‌ক্বাফ',
        meaning: 'বালুর পাহাড়',
        ayah: 35,
        ruku: 4,
        meccan: true,
      },
      {
        id: 47,
        arabic: 'محمّد',
        english: 'Muhammad',
        bangla: 'মুহাম্মদ',
        meaning: 'নবী মুহাম্মদ',
        ayah: 38,
        ruku: 4,
        meccan: false,
      },
      {
        id: 48,
        arabic: 'الفتح',
        english: 'Al-Fath',
        bangla: 'আল ফাত্‌হ',
        meaning: 'বিজয় (মক্কা বিজয়)',
        ayah: 29,
        ruku: 4,
        meccan: false,
      },
      {
        id: 49,
        arabic: 'الحجرات',
        english: 'Al-Hujurat',
        bangla: 'আল হুজুরাত',
        meaning: 'বাসগৃহসমূূহ',
        ayah: 18,
        ruku: 2,
        meccan: false,
      },
      {
        id: 50,
        arabic: 'ق',
        english: 'Qaf',
        bangla: 'ক্বাফ',
        meaning: 'আরবি বর্ণ ক্বাফ',
        ayah: 45,
        ruku: 3,
        meccan: true,
      },
  
  {
    id: 51,
    arabic: 'الذّاريات',
    english: 'Adh-Dhariyat',
    bangla: 'আয-যারিয়াত',
    meaning: 'বিক্ষেপকারী বাতাস',
    ayah: 60,
    ruku: 3,
    meccan: true,
  },
  {
    id: 52,
    arabic: 'الطّور',
    english: 'At-Tur',
    bangla: 'আত্ব তূর',
    meaning: 'পাহাড়',
    ayah: 49,
    ruku: 2,
    meccan: false,
  },
  {
    id: 53,
    arabic: 'النّجْم',
    english: 'An-Najm',
    bangla: 'আন-নাজম',
    meaning: 'তারা',
    ayah: 62,
    ruku: 3,
    meccan: true,
  },
  {
    id: 54,
    arabic: 'القمر',
    english: 'Al-Qamar',
    bangla: 'আল ক্বামার',
    meaning: 'চন্দ্র',
    ayah: 55,
    ruku: 3,
    meccan: true,
  },
  {
    id: 55,
    arabic: 'الرّحْمن',
    english: 'Ar-Rahman',
    bangla: 'আর রাহমান',
    meaning: 'অনন্ত করুণাময়',
    ayah: 78,
    ruku: 3,
    meccan: false,
  },
  {
    id: 56,
    arabic: 'الواقعة',
    english: 'Al-Waqi ah',
    bangla: 'আল-ওয়াকিয়াহ',
    meaning: 'নিশ্চিত ঘটনা',
    ayah: 96,
    ruku: 3,
    meccan: true,
  },
  {
    id: 57,
    arabic: 'الحديد',
    english: 'Al-Hadid',
    bangla: 'আল-হাদীদ',
    meaning: 'লোহা',
    ayah: 29,
    ruku: 4,
    meccan: false,
  },
  {
    id: 58,
    arabic: 'المجادلة',
    english: 'Al-Mujadila',
    bangla: 'আল-মুজাদালাহ',
    meaning: 'অনুযোগকারিণী',
    ayah: 22,
    ruku: 3,
    meccan: false,
  },
  {
    id: 59,
    arabic: 'الحشْر',
    english: 'Al-Hashr',
    bangla: 'আল-হাশর',
    meaning: 'সমাবেশ',
    ayah: 24,
    ruku: 3,
    meccan: false,
  },
  {
    id: 60,
    arabic: 'الممتحنة',
    english: 'Al-Mumtahanah',
    bangla: 'আল-মুমতাহিনাহ',
    meaning: 'নারী, যাকে পরীক্ষা করা হবে',
    ayah: 13,
    ruku: 2,
    meccan: false,
  },
  {
    id: 61,
    arabic: 'الصّفّ',
    english: 'As-Saff',
    bangla: 'আস-সাফ',
    meaning: 'সারবন্দী সৈন্যদল',
    ayah: 14,
    ruku: 2,
    meccan: false,
  },
  {
    id: 62,
    arabic: 'الجمعة',
    english: 'Al-Jumu ah',
    bangla: 'আল-জুমুআ',
    meaning: 'সম্মেলন/শুক্রবার',
    ayah: 11,
    ruku: 2,
    meccan: false,
  },
  {
    id: 63,
    arabic: 'المنافقون',
    english: 'Al-Munafiqun',
    bangla: 'আল-মুনাফিকুন',
    meaning: 'কপট বিশ্বাসীগণ',
    ayah: 11,
    ruku: 2,
    meccan: false,
  },
  {
    id: 64,
    arabic: 'التّغابن',
    english: 'At-Taghabun',
    bangla: 'আত-তাগাবুন',
    meaning: 'মোহ অপসারণ',
    ayah: 18,
    ruku: 2,
    meccan: false,
  },
  {
    id: 65,
    arabic: 'الطّلاق',
    english: 'At-Talaq',
    bangla: 'আত-তালাক',
    meaning: 'তালাক,বন্ধনমুক্তি',
    ayah: 12,
    ruku: 2,
    meccan: false,
  },
  {
    id: 66,
    arabic: 'التّحريم',
    english: 'At-Tahrim',
    bangla: 'আত-তাহরীম',
    meaning: 'নিষিদ্ধকরণ',
    ayah: 12,
    ruku: 2,
    meccan: false,
  },
  {
    id: 67,
    arabic: 'الملك',
    english: 'Al-Mulk',
    bangla: 'আল-মুলক',
    meaning: 'সার্বভৌম কর্তৃত্ব',
    ayah: 30,
    ruku: 2,
    meccan: true,
  },
  {
    id: 68,
    arabic: 'القلم',
    english: 'Al-Qalam',
    bangla: 'আল-কলম',
    meaning: 'কলম',
    ayah: 52,
    ruku: 2,
    meccan: true,
  },
  {
    id: 69,
    arabic: 'الحآقّة',
    english: 'Al-Haqqah',
    bangla: 'আল-হাক্কাহ',
    meaning: 'নিশ্চিত সত্য',
    ayah: 52,
    ruku: 2,
    meccan: true,
  },
  {
    id: 70,
    arabic: 'المعارج',
    english: 'Al-Ma arij',
    bangla: 'আল-মাআরিজ',
    meaning: 'উন্নয়নের সোপান',
    ayah: 44,
    ruku: 2,
    meccan: true,
  },
  {
    id: 71,
    arabic: 'نوح',
    english: 'Nuh',
    bangla: 'নূহ',
    meaning: 'নবী নূহ',
    ayah: 28,
    ruku: 2,
    meccan: true,
  },
  {
    id: 72,
    arabic: 'الجنّ',
    english: 'Al-Jinn',
    bangla: 'আল জ্বিন',
    meaning: 'জ্বিন সম্প্রদায়',
    ayah: 28,
    ruku: 2,
    meccan: true,
  },
  {
    id: 73,
    arabic: 'المزّمّل',
    english: 'Al-Muzzammil',
    bangla: 'আল মুজাম্মিল',
    meaning: 'বস্ত্র আচ্ছাদনকারী',
    ayah: 20,
    ruku: 2,
    meccan: true,
  },
  {
    id: 74,
    arabic: 'المدّشّر',
    english: 'Al-Muddaththir',
    bangla: 'আল মুদ্দাস্সির',
    meaning: 'পোশাক পরিহিত',
    ayah: 56,
    ruku: 2,
    meccan: true,
  },

  {
    id: 75,
    arabic: 'القيامة',
    english: 'Al-Qiyamah',
    bangla: 'আল-ক্বিয়ামাহ',
    meaning: 'পুনরুথান',
    ayah: 40,
    ruku: 2,
    meccan: true,
  },
  {
    id: 76,
    arabic: 'الدَّهْرِ',
    english: 'Ad-Dahr',
    bangla: 'আদ-দাহর',
    meaning: 'মানুষ',
    ayah: 31,
    ruku: 2,
    meccan: false,
  },
  {
    id: 77,
    arabic: 'المرسلت',
    english: 'Al-Mursalat',
    bangla: 'আল-মুরসালাত',
    meaning: 'প্রেরিত পুরুষবৃন্দ',
    ayah: 50,
    ruku: 2,
    meccan: true,
  },
  {
    id: 78,
    arabic: 'النّبا',
    english: 'An-Naba',
    bangla: 'আন নাবা',
    meaning: 'মহাসংবাদ',
    ayah: 40,
    ruku: 2,
    meccan: true,
  },
  {
    id: 79,
    arabic: 'النّزعت',
    english: 'An-Nazi at',
    bangla: 'আন নাযিয়াত',
    meaning: 'প্রচেষ্টাকারী',
    ayah: 46,
    ruku: 2,
    meccan: true,
  },
  {
    id: 80,
    arabic: 'عبس',
    english: 'Abasa',
    bangla: 'আবাসা',
    meaning: 'তিনি ভ্রুকুটি করলেন',
    ayah: 42,
    ruku: 1,
    meccan: true,
  },
  {
    id: 81,
    arabic: 'التّكوير',
    english: 'At-Takwir',
    bangla: 'আত-তাকভীর',
    meaning: 'অন্ধকারাচ্ছন্ন',
    ayah: 29,
    ruku: 1,
    meccan: true,
  },
  {
    id: 82,
    arabic: 'الانفطار',
    english: 'Al-Infitar',
    bangla: 'আল-ইনফিতার',
    meaning: 'বিদীর্ণ করা',
    ayah: 19,
    ruku: 1,
    meccan: true,
  },
  {
    id: 83,
    arabic: 'المطفّفين',
    english: 'Al-Mutaffifin',
    bangla: 'আত মুত্বাফ্‌ফিফীন',
    meaning: 'প্রতারকগণ',
    ayah: 36,
    ruku: 1,
    meccan: true,
  },
  {
    id: 84,
    arabic: 'الانشقاق',
    english: 'Al-Inshiqaq',
    bangla: 'আল ইন‌শিকাক',
    meaning: 'খন্ড-বিখন্ড করণ',
    ayah: 25,
    ruku: 1,
    meccan: true,
  },
  {
    id: 85,
    arabic: 'البروج',
    english: 'Al-Buruj',
    bangla: 'আল-বুরুজ',
    meaning: 'নক্ষত্রপুঞ্জ',
    ayah: 22,
    ruku: 1,
    meccan: true,
  },
  {
    id: 86,
    arabic: 'الطّارق',
    english: 'At-Tariq',
    bangla: 'আত-তারিক্ব',
    meaning: 'রাতের আগন্তুক',
    ayah: 17,
    ruku: 1,
    meccan: true,
  },
  {
    id: 87,
    arabic: 'الأعلى',
    english: 'Al-A la',
    bangla: 'আল আ\'লা',
    meaning: 'সর্বোর্ধ্ব',
    ayah: 19,
    ruku: 1,
    meccan: true,
  },
  {
    id: 88,
    arabic: 'الغاشية',
    english: 'Al-Ghashiyah',
    bangla: 'আল গাশিয়াহ্‌',
    meaning: 'বিহ্বলকর ঘটনা',
    ayah: 26,
    ruku: 1,
    meccan: true,
  },
  {
    id: 89,
    arabic: 'الفجر',
    english: 'Al-Fajr',
    bangla: 'আল ফাজ্‌র',
    meaning: 'ভোরবেলা',
    ayah: 30,
    ruku: 1,
    meccan: true,
  },
  {
    id: 90,
    arabic: 'البلد',
    english: 'Al-Balad',
    bangla: 'আল বালাদ',
    meaning: 'নগর',
    ayah: 20,
    ruku: 1,
    meccan: true,
  },
  {
    id: 91,
    arabic: 'الشّمس',
    english: 'Ash-Shams',
    bangla: 'আশ-শাম্‌স',
    meaning: 'সূর্য্য',
    ayah: 15,
    ruku: 1,
    meccan: true,
  },
  {
    id: 92,
    arabic: 'الليل',
    english: 'Al-Lail',
    bangla: 'আল লাইল',
    meaning: 'রাত্রি',
    ayah: 21,
    ruku: 1,
    meccan: true,
  },
  {
    id: 93,
    arabic: 'الضحى',
    english: 'Ad-Duha',
    bangla: 'আদ-দুহা',
    meaning: 'পূর্বাহ্নের সূর্যকিরণ',
    ayah: 11,
    ruku: 1,
    meccan: true,
  },
  {
    id: 94,
    arabic: 'الشرح',
    english: 'Al-Inshirah',
    bangla: 'আল ইনশিরাহ',
    meaning: 'বক্ষ প্রশস্তকরণ',
    ayah: 8,
    ruku: 1,
    meccan: true,
  },
  {
    id: 95,
    arabic: 'التين',
    english: 'At-Tin',
    bangla: 'ত্বীন',
    meaning: 'ডুমুর',
    ayah: 8,
    ruku: 1,
    meccan: true,
  },
  {
    id: 96,
    arabic: 'العلق',
    english: 'Al-Alaq',
    bangla: 'আলাক্ব',
    meaning: 'রক্তপিন্ড',
    ayah: 19,
    ruku: 1,
    meccan: true,
  },
  {
    id: 97,
    arabic: 'القدر',
    english: 'Al-Qadr',
    bangla: 'ক্বদর',
    meaning: 'পরিমাণ',
    ayah: 5,
    ruku: 1,
    meccan: true,
  },
  {
    id: 98,
    arabic: 'البينة',
    english: 'Al-Bayyinah',
    bangla: 'বাইয়্যিনাহ',
    meaning: 'সুস্পষ্ট প্রমাণ',
    ayah: 8,
    ruku: 1,
    meccan: false,
  },
  {
    id: 99,
    arabic: 'الزلزلة',
    english: 'Az-Zalzalah',
    bangla: 'যিলযাল',
    meaning: 'ভূমিকম্প',
    ayah: 8,
    ruku: 1,
    meccan: false,
  },
  {
    id: 100,
    arabic: 'العاديات',
    english: 'Al-Adiyat',
    bangla: 'আল-আদিয়াত',
    meaning: 'অভিযানকারী',
    ayah: 11,
    ruku: 1,
    meccan: true,
  },
  {
    id: 101,
    arabic: 'القارعة',
    english: 'Al-Qari ah',
    bangla: 'ক্বারিয়াহ',
    meaning: 'মহাসংকট',
    ayah: 11,
    ruku: 1,
    meccan: true,
  },
  {
    id: 102,
    arabic: 'التكاثر',
    english: 'At-Takathur',
    bangla: 'তাকাসুর',
    meaning: 'প্রাচুর্যের প্রতিযোগিতা',
    ayah: 8,
    ruku: 1,
    meccan: true,
  },
  {
    id: 103,
    arabic: 'العصر',
    english: 'Al-Asr',
    bangla: 'আছর',
    meaning: 'অপরাহ্ন',
    ayah: 3,
    ruku: 1,
    meccan: true,
  },
  {
    id: 104,
    arabic: 'الهمزة',
    english: 'Al-Humazah',
    bangla: 'হুমাযাহ',
    meaning: 'পরনিন্দাকারী',
    ayah: 9,
    ruku: 1,
    meccan: true,
  },
  {
    id: 105,
    arabic: 'الفيل',
    english: 'Al-Fil',
    bangla: 'ফীল',
    meaning: 'হাতি',
    ayah: 5,
    ruku: 1,
    meccan: true,
  },
  {
    id: 106,
    arabic: 'قريش',
    english: 'Quraish',
    bangla: 'কুরাইশ',
    meaning: 'কুরাইশ গোত্র',
    ayah: 4,
    ruku: 1,
    meccan: true,
  },
  {
    id: 107,
    arabic: 'الماعون',
    english: 'Al-Ma un',
    bangla: 'মাউন',
    meaning: 'সাহায্য-সহায়তা',
    ayah: 7,
    ruku: 1,
    meccan: true,
  },
  {
    id: 108,
    arabic: 'الكوثر',
    english: 'Al-Kawthar',
    bangla: 'কাওসার',
    meaning: 'প্রাচুর্য',
    ayah: 3,
    ruku: 1,
    meccan: true,
  },
  {
    id: 109,
    arabic: 'الكافرون',
    english: 'Al-Kafirun',
    bangla: 'কাফিরুন',
    meaning: 'অস্বীকারকারীগণ',
    ayah: 6,
    ruku: 1,
    meccan: true,
  },
  {
    id: 110,
    arabic: 'النصر',
    english: 'An-Nasr',
    bangla: 'নাসর',
    meaning: 'বিজয়,সাহায্য',
    ayah: 3,
    ruku: 1,
    meccan: false,
  },
  {
    id: 111,
    arabic: 'المسد',
    english: 'Al-Masad',
    bangla: 'লাহাব',
    meaning: 'জ্বলন্ত অঙ্গার',
    ayah: 5,
    ruku: 1,
    meccan: true,
  },
  {
    id: 112,
    arabic: 'الإخلاص',
    english: 'Al-Ikhlas',
    bangla: 'আল-ইখলাস',
    meaning: 'একনিষ্ঠতা',
    ayah: 4,
    ruku: 1,
    meccan: true,
  },
  {
    id: 113,
    arabic: 'الفلق',
    english: 'Al-Falaq',
    bangla: 'আল-ফালাক',
    meaning: 'নিশিভোর',
    ayah: 5,
    ruku: 1,
    meccan: true,
  },
  {
    id: 114,
    arabic: 'الناس',
    english: 'An-Nas',
    bangla: 'আন-নাস',
    meaning: 'মানবজাতি',
    ayah: 6,
    ruku: 1,
    meccan: true,
  },
];
export default surahs;